////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$AddSkill", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class AddSkillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short SkillVnum { get; set; }

        public static string ReturnHelp()
        {
            return "$AddSkill SKILLVNUM";
        }

        #endregion
    }
}