////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$Lvl", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ChangeLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Level { get; set; }

        public static string ReturnHelp() => "$Lvl LEVEL";

        #endregion
    }
}