////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$HeroLvl", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ChangeHeroLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte HeroLevel { get; set; }

        public static string ReturnHelp() => "$HeroLvl HEROLEVEL";

        #endregion
    }
}