////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$CharEdit", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class CharacterEditPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public string Property { get; set; }

        [PacketIndex(1, serializeToEnd: true)] public string Data { get; set; }

        public static string ReturnHelp()
        {
            return "$CharEdit PROPERTYNAME DATA";
        }

        #endregion
    }
}