////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$HairColor", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class HairColorPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public HairColorType HairColor { get; set; }

        public static string ReturnHelp()
        {
            return "$HairColor COLORID";
        }

        #endregion
    }
}