////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$HairStyle", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class HairStylePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public HairStyleType HairStyle { get; set; }

        public static string ReturnHelp() => "$HairStyle STYLEID";

        #endregion
    }
}