////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$HeroXpRate", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class HeroXpRatePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)] public int Value { get; set; }

        public static string ReturnHelp()
        {
            return "$HeroXpRate VALUE";
        }

        #endregion
    }
}