////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$KickSession", PassNonParseablePacket = true, Authority = AuthorityType.Moderator)]
    public class KickSessionPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string AccountName { get; set; }

        [PacketIndex(1)]
        public long? SessionId { get; set; }

        public static string ReturnHelp() => "$KickSession ACCOUNTNAME SESSIONID(?)";

        #endregion
    }
}