////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$MapPVP", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class MapPvpPacket : PacketDefinition
    {
        public static string ReturnHelp()
        {
            return "$MapPVP";
        }
    }
}