////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$SearchMonster", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class SearchMonsterPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Page { get; set; }

        [PacketIndex(1, SerializeToEnd = true)]
        public string Name { get; set; }

        public static string ReturnHelp() => "$SearchMonster PAGE NAME(*)";

        #endregion
    }
}