////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$ShutdownAll", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ShutdownAllPacket : PacketDefinition
    {
        [PacketIndex(0)] public string WorldGroup { get; set; }

        public static string ReturnHelp()
        {
            return "$ShutdownAll WORLDGROUP(*)";
        }

        public override string ToString()
        {
            return $"ShutdownAll Command WorldGroup: {WorldGroup}";
        }
    }
}