////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$Warn", PassNonParseablePacket = true, Authority = AuthorityType.Moderator)]
    public class WarningPacket : PacketDefinition
    {
        #region Methods

        public override string ToString() => $"Warning Command CharacterName: {CharacterName} Message: {Reason}";

        #endregion

        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1, serializeToEnd: true)]
        public string Reason { get; set; }

        public static string ReturnHelp() => "$Warn CHARACTERNAME REASON";

        #endregion
    }
}