////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using NosSharp.Enums;
using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.CommandPackets
{
    [PacketHeader("$Zoom", PassNonParseablePacket = true, Authority = AuthorityType.GameMaster)]
    public class ZoomPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Value { get; set; }

        public static string ReturnHelp()
        {
            return "$Zoom VALUE";
        }

        #endregion
    }
}