////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("c_skill")]
    public class CSkillPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}