////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("escape")]
    public class EscapePacket : PacketDefinition
    {
        #region Properties        

        #endregion
    }
}