////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("npinfo")]
    public class NpinfoPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Page { get; set; }

        #endregion
    }
}