////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("preq")]
    public class PreqPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}