////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("rsel")]
    public class RSelPacket : PacketDefinition
    {
        #region Properties        

        #endregion
    }
}