////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("rstart")]
    public class RStartPacket : PacketDefinition
    {
        #region Properties        

        [PacketIndex(0)]
        public byte? Type { get; set; }
        
        #endregion
    }
}