////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("shopclose")]
    public class ShopClosePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}