////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core.Serializing;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("today_cts")]
    public class TodayPacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}