// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Aphrodite93 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aphrodite93));
        
        string IMigrationMetadata.Id
        {
            get { return "201711191214159_Aphrodite93"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
